(function (root) {
  // Canonical 45 frontend strategy IDs, in display order.
  // MUST stay byte-identical to the keys written by deploy/quantsite/calc_rankings.py
  // (frontend_strategy_specs) into leaderboard.json `by_engine`. Shared by terminal.js
  // and live-room.js so both pages always resolve the same strategy_id <-> tier map.
  root.QA_ENGINE_LIST = [
    ["dual", "free"],
    ["ribbon", "free"],
    ["rsi", "free"],
    ["squeeze", "free"],
    ["atr", "free"],
    ["qe", "master"],
    ["dm", "master"],
    ["sn", "master"],
    ["eh", "master"],
    ["gw", "master"],
    ["ns", "master"],
    ["sf", "master"],
    ["qk", "master"],
    ["hs", "master"],
    ["hg", "master"],
    ["strat-001", "free"],
    ["strat-002", "free"],
    ["strat-003", "free"],
    ["strat-004", "free"],
    ["strat-005", "free"],
    ["strat-006", "free"],
    ["strat-007", "free"],
    ["strat-008", "free"],
    ["strat-009", "free"],
    ["strat-010", "free"],
    ["strat-011", "master"],
    ["strat-012", "master"],
    ["strat-013", "master"],
    ["strat-014", "master"],
    ["strat-015", "master"],
    ["strat-016", "master"],
    ["strat-017", "master"],
    ["strat-018", "master"],
    ["strat-019", "master"],
    ["strat-020", "master"],
    ["strat-021", "master"],
    ["strat-022", "master"],
    ["strat-023", "master"],
    ["strat-024", "master"],
    ["strat-025", "master"],
    ["strat-026", "master"],
    ["strat-027", "master"],
    ["strat-028", "master"],
    ["strat-029", "master"],
    ["strat-030", "master"],
  ];
})(window);
